apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: production
spec:
  version: 7.6.1
  http:
    tls:
    # Change to false if you want to install full TLS enabled
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        clusterIP: None
  count: 1
  elasticsearchRef:
    name: production
  config:
    elasticsearch:
      #D20# Change this to the namespace you want to use
      hosts: http://production-es-coordinator.elastic.svc:9200
    server.host: 0.0.0.0
    server.name: ${HOSTNAME}
    elasticsearch.requestTimeout: 90000
  secureSettings:
    - secretName: kibana-secret-settings
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 8Gi
              cpu: 4
            limits:
              memory: 8Gi
              cpu: 4
---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-secret-settings
type: Opaque
data:
  xpack.security.encryptionKey: OTRkMjI2M2IxZWFkNzE2YWUyMjgyNzcwNDlmMTk5NzVhZmY4NjRmYjRmY2ZlNDE5Yzk1MTIzYzFlOTA5MzhjZA==

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  # annotations:
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  #   nginx.ingress.kubernetes.io/secure-backends: "true"
  name: kibana-ingress
spec:
  #D20# Change these to the ingress FQDN you have setup
  tls:
  - hosts:
    - kibana.ingress.se4.diamanti.com
  rules:
  - host: kibana.ingress.se4.diamanti.com
    http:
      paths:
      - backend:
          serviceName: production-kb-http
          servicePort: 5601
        path: /
